// Build-time verification: the launcher has just regenerated
// src-tauri/capabilities/companion.json and src-tauri/generated/desktop-origin-provenance.json.
// This script:
//   * fails fast when TIDE_BOT_DESKTOP_GENERATION_NONCE is missing or stale
//   * re-hashes the tracked resolver and template
//   * rejects drift between provenance.digests and the actual generated bytes
//   * emits the accepted nonce through cargo:rustc-env so the compiled binary
//     refuses to load a stale provenance
//   * hands the AppManifest to tauri_build so Tauri's permission table is
//     generated from capabilities/companion.json + permissions/companion.toml

use sha2::{Digest, Sha256};
use std::env;
use std::fs;
use std::path::Path;
use std::process::ExitCode;

const NONCE_ENV: &str = "TIDE_BOT_DESKTOP_GENERATION_NONCE";

fn sha256_hex(bytes: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    let digest = hasher.finalize();
    let mut out = String::with_capacity(64);
    for byte in digest {
        out.push_str(&format!("{:02x}", byte));
    }
    out
}

fn fail(message: &str) -> ExitCode {
    eprintln!("build.rs: {message}");
    ExitCode::FAILURE
}

fn validate_provenance(manifest_dir: &str) -> Result<(String, String), ExitCode> {
    let desktop_dir = manifest_dir;
    let nonce = match env::var(NONCE_ENV) {
        Ok(value) if !value.is_empty() => value,
        _ => {
            return Err(fail(&format!(
                "{NONCE_ENV} is required; build-desktop.mjs is the only supported entry point"
            )))
        }
    };


    let capability_path = Path::new(desktop_dir).join("capabilities").join("companion.json");
    let provenance_path = Path::new(desktop_dir).join("generated").join("desktop-origin-provenance.json");
    if !capability_path.is_file() {
        return Err(fail(&format!("missing generated capability at {}", capability_path.display())));
    }
    if !provenance_path.is_file() {
        return Err(fail(&format!("missing generated provenance at {}", provenance_path.display())));
    }

    let capability_bytes = fs::read(&capability_path)
        .map_err(|error| fail(&format!("could not read capability: {error}")))?;
    let provenance_bytes = fs::read(&provenance_path)
        .map_err(|error| fail(&format!("could not read provenance: {error}")))?;
    let capability_text = std::str::from_utf8(&capability_bytes)
        .map_err(|_| fail("capability JSON is not valid UTF-8"))?;
    let provenance_text = std::str::from_utf8(&provenance_bytes)
        .map_err(|_| fail("provenance JSON is not valid UTF-8"))?;

    let provenance: serde_json::Value = serde_json::from_str(provenance_text)
        .map_err(|error| fail(&format!("provenance JSON is not parseable: {error}")))?;
    if provenance.get("schemaVersion").and_then(serde_json::Value::as_str) != Some("tide-bot-desktop-origins/v1") {
        return Err(fail("provenance schemaVersion is missing or not tide-bot-desktop-origins/v1"));
    }
    let provenance_nonce = provenance
        .get("generationNonce")
        .and_then(serde_json::Value::as_str)
        .unwrap_or_default()
        .to_string();
    if provenance_nonce.is_empty() {
        return Err(fail("provenance is missing generationNonce"));
    }
    if provenance_nonce != nonce {
        return Err(fail("provenance.generationNonce does not match TIDE_BOT_DESKTOP_GENERATION_NONCE; rerun scripts/build-desktop.mjs"));
    }

    let resolver_path = Path::new(desktop_dir).join("..").join("scripts").join("desktop-origins.mjs");
    let template_path = Path::new(desktop_dir).join("templates").join("companion.capability.template.json");
    let resolver_bytes = fs::read(&resolver_path)
        .map_err(|error| fail(&format!("could not read resolver: {error}")))?;
    let template_bytes = fs::read(&template_path)
        .map_err(|error| fail(&format!("could not read template: {error}")))?;

    let expected_resolver_sha = sha256_hex(&resolver_bytes);
    let expected_template_sha = sha256_hex(&template_bytes);
    let expected_capability_sha = sha256_hex(&capability_bytes);

    let recorded_resolver_sha = provenance
        .get("resolverSha256")
        .and_then(serde_json::Value::as_str)
        .unwrap_or_default();
    let recorded_template_sha = provenance
        .get("templateSha256")
        .and_then(serde_json::Value::as_str)
        .unwrap_or_default();
    let recorded_capability_sha = provenance
        .get("capabilitySha256")
        .and_then(serde_json::Value::as_str)
        .unwrap_or_default();

    if recorded_resolver_sha != expected_resolver_sha {
        return Err(fail("provenance.resolverSha256 does not match the tracked resolver"));
    }
    if recorded_template_sha != expected_template_sha {
        return Err(fail("provenance.templateSha256 does not match the tracked template"));
    }
    if recorded_capability_sha != expected_capability_sha {
        return Err(fail("provenance.capabilitySha256 does not match the freshly written capability"));
    }

    let capability: serde_json::Value = serde_json::from_str(capability_text)
        .map_err(|error| fail(&format!("capability JSON is not parseable: {error}")))?;
    let windows = capability
        .get("windows")
        .and_then(serde_json::Value::as_array)
        .map(|items| items.iter().filter_map(serde_json::Value::as_str).collect::<Vec<_>>());
    if windows.as_deref() != Some(["companion"].as_slice()) {
        return Err(fail("capability.windows must be exactly [\"companion\"]"));
    }
    let permissions = capability
        .get("permissions")
        .and_then(serde_json::Value::as_array)
        .map(|items| items.iter().filter_map(serde_json::Value::as_str).collect::<Vec<_>>());
    if permissions.as_deref() != Some(["allow-show-main-window"].as_slice()) {
        return Err(fail("capability.permissions must be exactly [\"allow-show-main-window\"]"));
    }
    let remote_urls: Vec<String> = capability
        .get("remote")
        .and_then(|remote| remote.get("urls"))
        .and_then(serde_json::Value::as_array)
        .map(|items| items.iter().filter_map(serde_json::Value::as_str).map(str::to_string).collect())
        .unwrap_or_default();
    if remote_urls.is_empty() {
        return Err(fail("capability.remote.urls must be a non-empty array"));
    }

    println!("cargo:warning=desktop shell binding nonce={}", &nonce[..nonce.len().min(16)]);
    println!("cargo:warning=capability sha256={}", &expected_capability_sha[..16]);
    println!("cargo:rustc-env=TIDE_BOT_DESKTOP_GENERATION_NONCE={nonce}");
    println!("cargo:rustc-env=TIDE_BOT_DESKTOP_EXPECTED_RESOLVER_SHA={expected_resolver_sha}");
    println!("cargo:rustc-env=TIDE_BOT_DESKTOP_EXPECTED_TEMPLATE_SHA={expected_template_sha}");
    println!("cargo:rustc-env=TIDE_BOT_DESKTOP_EXPECTED_CAPABILITY_SHA={expected_capability_sha}");
    println!("cargo:rustc-env=TIDE_BOT_DESKTOP_REMOTE_URLS={}", remote_urls.join("|"));
    println!("cargo:rerun-if-env-changed={NONCE_ENV}");
    println!("cargo:rerun-if-changed={}", capability_path.display());
    println!("cargo:rerun-if-changed={}", provenance_path.display());
    println!("cargo:rerun-if-changed={}", resolver_path.display());
    println!("cargo:rerun-if-changed={}", template_path.display());

    Ok((nonce, expected_capability_sha))
}

fn main() -> ExitCode {
    let manifest_dir = match env::var("CARGO_MANIFEST_DIR") {
        Ok(value) => value,
        Err(_) => return fail("CARGO_MANIFEST_DIR is unset"),
    };

    if let Err(code) = validate_provenance(&manifest_dir) {
        return code;
    }

    tauri_build::build();
    ExitCode::SUCCESS
}
